"""add total_costs and total_days columns

Revision ID: 7c7ad94b73b7
Revises: 8c35d33a79d3
Create Date: 2024-07-15 12:05:38.421634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c7ad94b73b7'
down_revision: Union[str, None] = '8c35d33a79d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('total_costs', sa.Integer(), sa.Computed('(date_to  - date_from) * price', ), nullable=True))
    op.add_column('bookings', sa.Column('total_days', sa.Integer(), sa.Computed('(date_to -  date_from)', ), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'total_days')
    op.drop_column('bookings', 'total_costs')
    # ### end Alembic commands ###
