"""dlt image_id from bookings table

Revision ID: 8c35d33a79d3
Revises: 4cbd41306821
Create Date: 2024-07-15 00:06:22.315047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c35d33a79d3'
down_revision: Union[str, None] = '4cbd41306821'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'date_from',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('bookings', 'date_to',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('bookings', 'image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('bookings', 'date_to',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('bookings', 'date_from',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('bookings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
